### ISSUE TITLE
How to compile the swift application ?

### ISSUE THREAD

**Issue by obilger** [alessandro308/YeelightController#1]
Alessandro,
how do we compile your application with xcode ?

kind regards

**Comment by alessandro308** [comment]
I just push a new code with XCode Project. Download it, import and then run. Remember that you must set IP bulb in the Yeelight.swift class constructor in order to use this app, or implement a multicast discovery to recover it.

**Comment by obilger** [comment]
Thanks  a bunch Alessandro

**Comment by obilger** [comment]
Alessandro, 
It looks like the project is incomplete and AppDelegate.swift is missing
kind regards
Olivier

**Comment by alessandro308** [comment]
My refuse. I have added AppDelegate to project and committed the changing. Try now, it compile on my machine but some missing reference can appear on other machine. I'm waiting for a response =)

**Comment by obilger** [comment]
I’m making some progress !
I had to replace info.list and bas.lproj in your project to the ones on the disk and the app is compiling.

But I  have a fatal exception in Yeelight.swift when running the application

 func updateProprieties(){
        let d = sendCmdReply(id: i, method: "get_prop", params: ["power", "bright", "ct", "rgb", "hue", "sat", "color_mode", "flowing", "delayoff", "flow_params", "music_on", "name"], printMessage: "getProprieties")
        let res = d["result"] as! [Any]
        if(res[0] as! String == "on"){
            proprieties.power = true
        } else {
            proprieties.power = false
        }

connectionTimeout
fatal error: unexpectedly found nil while unwrapping an Optional value
2017-11-01 06:58:35.458729+0100 Yeelight-Controller[3438:77498] fatal error: unexpectedly found nil while unwrapping an Optional value

So i assume I did not update the IP at the right places.
I have updated it in 

MainViewController.swift: let bulb = Yeelight(ip: “192.168.1.26”)
Yeelight.swift; self.IP = “192.168.1.26” //TODO Find IP


when pinging the address, I get an answer and the bulb is in developper mode.

Is there anything I’m missing ?
by the way, I know nothing to swift ! maybe time to learn for me …

thanks
Olivier

**Comment by alessandro308** [comment]
In order to set your ip you need to change only the value in the MainViewController.swift, line 15. The value you changed in the Yeelight.swift doesn't affect any part of application because that method (init()) is never called, since the constructor used is init(IP:String).

In any case, that error appears when there is some network error. HAve you activate "Developer Mode" from Xiaomi App for your bulb? Without this mode you cannot communicate with the bulb and use this app

**Comment by niccolospa** [comment]
I'm getting the same error, I changed only the value in MainViewController.swift, line 15. But still getting `connection timeout` in console. I confirm having developer mode active on the bulb. I'm also getting some warning such as:
-Implicit declaration of function 'select' is invalid in C99 in ytcpsocket.c
-This function declaration is not a prototype in ytcpsocket.c
-'substring(to:)' is deprecated: Please use String slicing subscript with a 'partial range upto' operator. line 147 Yeelight.swift
-Warning: The Copy Bundle Resources build phase contains this target's Info.plist file 'Yeelight-Controller/Info.plist'.
